Feature/extract components from cv pages
ds-consultants/dynamic-cv-react pull request #9
Opened 2018-05-07 08:50 UTC by MontJamesmont

2018-05-07 09:35 UTC, StudentDawid requested changes

2018-05-07 09:35 UTC, StudentDawid commented on src/cv/educationContainer/EducationContainer.js
> +    const educationSource = props.educationSource;
Better way:
const {userEducations, educationSource} = props;

2018-05-07 09:35 UTC, StudentDawid commented on src/cv/educationContainer/EducationContainer.js
> +        educationList = userEducations.map(function (education, index) {
Better way :
const educationList = user. education ? user.education.map(function (education, index) {...}) : [];

2018-05-07 09:35 UTC, StudentDawid commented on src/cv/educationContainer/education/Education.js
> +        let { education } = this.props;
Can be const

2018-05-07 09:35 UTC, StudentDawid commented on src/cv/expectationContainer/ExpectationContainer.js
> +    const professionalExpectations = props.professionalExpectations;
Better way:
const {sourcesTarget, professionalExpectations} = props;

2018-05-07 09:35 UTC, StudentDawid commented on src/cv/experienceContainer/ExperienceContainer.js
> +    const experienceSource = props.experienceSource;
Better way:
const {userExperience, experienceSource} = props;

2018-05-07 09:35 UTC, StudentDawid commented on src/cv/experienceContainer/ExperienceContainer.js
> +        experiencesList = userExperience.map(function (experience, index) {
Better way :
const experiencesList = user.experience ? user.experience.map(function (experience, index) {...}) : [];

2018-05-07 09:35 UTC, StudentDawid commented on src/cv/experienceContainer/experience/Experience.js
> +        let { experience } = this.props;
Can be const

2018-05-07 09:35 UTC, StudentDawid commented on src/cv/personalNoteContainer/PersonalNoteContainer.js
> +    const userPersonalNote = props.userPersonalNote;
Better way:
const {sourcesProfile, userPersonalNote} = props;

2018-05-07 09:35 UTC, StudentDawid commented on src/cv/skillsetContainer/SkillsetContainer.js
> +    const userSkillset = props.userSkillset;
Better way:
const {sourcesSkillset, userSkillset} = props;

2018-05-07 09:35 UTC, StudentDawid commented on src/cv/skillsetContainer/SkillsetContainer.js
> +        skillsetList = (
Better way :
const skillsetList = userSkillset ? (<Skillset skillset={userSkillset} />) : [];

2018-05-07 09:35 UTC, StudentDawid commented on src/cv/skillsetContainer/skillset/Skillset.js
> +        let { skillset } = this.props;
Can be const

2018-05-07 09:35 UTC, StudentDawid commented on src/cv/standardSection/StandardSection.js
> +    const content = props.content;
Better way:
const {title, imgSrc, content} = props;

2018-05-07 09:35 UTC, StudentDawid commented on src/cv/titleContainer/TitleContainer.js
> +    const user = props.user;
Better way:
const {sources, user} = props;

2018-05-07 12:17 UTC, MontJamesmont commented on src/cv/educationContainer/EducationContainer.js
> +    const educationSource = props.educationSource;
fixed in 7705c5ea5848f4633cca70b667caf424c1187e85

2018-05-07 12:17 UTC, MontJamesmont commented on src/cv/educationContainer/EducationContainer.js
> +        educationList = userEducations.map(function (education, index) {
fixed in 7705c5e

2018-05-07 12:17 UTC, MontJamesmont commented on src/cv/educationContainer/education/Education.js
> +        let { education } = this.props;
fixed in 7705c5e

2018-05-07 12:18 UTC, MontJamesmont commented on src/cv/expectationContainer/ExpectationContainer.js
> +    const professionalExpectations = props.professionalExpectations;
fixed in 7705c5e

2018-05-07 12:18 UTC, MontJamesmont commented on src/cv/experienceContainer/ExperienceContainer.js
> +    const experienceSource = props.experienceSource;
fixed in 7705c5e

2018-05-07 12:18 UTC, MontJamesmont commented on src/cv/skillsetContainer/SkillsetContainer.js
> +    const userSkillset = props.userSkillset;
fixed in 7705c5e

2018-05-07 12:18 UTC, MontJamesmont commented on src/cv/skillsetContainer/SkillsetContainer.js
> +        skillsetList = (
fixed in 7705c5e

2018-05-07 12:18 UTC, MontJamesmont commented on src/cv/skillsetContainer/skillset/Skillset.js
> +        let { skillset } = this.props;
fixed in a3289ca5011e616ec4192b2eece768266c6cf690

2018-05-07 12:18 UTC, MontJamesmont commented on src/cv/standardSection/StandardSection.js
> +    const content = props.content;
fixed in 7705c5e

2018-05-07 12:19 UTC, MontJamesmont commented on src/cv/titleContainer/TitleContainer.js
> +    const user = props.user;
fixed in 7705c5e

2018-05-08 06:32 UTC, StudentDawid approved these changes

2018-05-08 07:34 UTC, merged